name: Java CI with Maven

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
    - name: Build Maven and copy output
      run: bash build_and_out.sh

    - name: Upload build output
      uses: actions/upload-artifact@v4
      with:
        name: caciocavallo
        path: out
